import { describe, expect, it } from "bun:test";
import vectors from "../../tests/vectors/axelarClientVectors.json";
import {
  type AxelarMessage,
  type AxelarRouteKind,
  axelarApprovalSteps,
  axelarFundInstruction,
  axelarInitializeInstruction,
  axelarReceiveSteps,
  axelarRouteAddress,
  axelarSetChainMappingInstruction,
  axelarSubmitInstruction,
  decodeAxelarConfig,
  decodeAxelarRoute,
} from "./index";

// Generated by `client_instruction_vectors` in lifi-intent-svm
// (tests/litesvm-unit/core_tests/axelar_litesvm). Requests use the reference
// builder's JSON shape; results there are unprefixed hex and decimal strings.
type Request = Record<string, any>;

function run(r: Request): unknown {
  const hex = (v: string) => `0x${v}` as const;
  const message = r.message as AxelarMessage;
  switch (r.operation) {
    case "config":
      return decodeAxelarConfig(hex(r.data));
    case "route":
      return decodeAxelarRoute(hex(r.data));
    case "routeAddress":
      return { route: axelarRouteAddress(r.name) };
    case "setChainMapping":
      return axelarSetChainMappingInstruction({
        owner: r.payer,
        name: r.name,
        chainId: BigInt(r.chainId),
        kind: r.kind,
      });
    case "initialize":
      return axelarInitializeInstruction({
        payer: r.payer,
        gateway: r.gateway,
        gasService: r.gasService,
        chainName: r.chainName,
      });
    case "fund":
      return axelarFundInstruction({
        payer: r.payer,
        gasService: r.gasService,
        messageId: message.cc_id.message_id,
        amount: BigInt(r.amount),
      });
    case "submit":
      return axelarSubmitInstruction({
        payer: r.payer,
        gateway: r.gateway,
        gasService: r.gasService,
        source: r.source,
        destinationChain: r.destinationChain,
        recipientOracle: hex(r.recipientOracle),
        payload: hex(r.payload),
        gasAmount: BigInt(r.gasAmount),
        deliveryMode: r.deliveryMode,
        consume: r.consume,
      });
    case "approve":
      return axelarApprovalSteps({
        payer: r.payer,
        gateway: r.gateway,
        message,
        executeData: hex(r.executeData),
      });
    case "receive":
      return axelarReceiveSteps({
        payer: r.payer,
        gateway: r.gateway,
        message,
        payload: hex(r.payload),
        sourceChainId: BigInt(r.sourceChainId),
        sourceKind: r.sourceKind as AxelarRouteKind,
      });
  }
  throw new Error(`Unknown operation ${r.operation}`);
}

const normalize = (value: unknown): unknown =>
  JSON.parse(
    JSON.stringify(value, (_, v) =>
      typeof v === "bigint"
        ? v.toString()
        : typeof v === "string" && v.startsWith("0x")
          ? v.slice(2)
          : v,
    ),
  );

describe("Axelar builders match the Rust reference vectors", () => {
  for (const v of vectors as {
    name: string;
    request: Request;
    result?: unknown;
    error?: true;
  }[]) {
    it(v.name, () => {
      if (v.error) expect(() => run(v.request)).toThrow();
      else expect(normalize(run(v.request))).toEqual(v.result);
    });
  }
});
