import { describe, expect, it } from "bun:test";
import { base58 } from "@scure/base";
import { keccak256 } from "viem";
import vectors from "../../tests/vectors/axelarClientVectors.json";
import { toBytes, u128Le } from "./bytes";
import {
  type AxelarAddressKind,
  type AxelarMessage,
  INTENTS_PROTOCOL_PROGRAM,
  axelarApprovalSteps,
  axelarFundInstruction,
  axelarInitializeInstruction,
  axelarRenounceOwnershipInstruction,
  axelarReceiveSteps,
  axelarRouteAddress,
  axelarSetChainMappingInstruction,
  axelarTransferOwnershipInstruction,
  axelarSubmitInstruction,
  decodeAxelarAddress,
  decodeAxelarConfig,
  decodeAxelarRoute,
  findSolanaProgramAddress,
} from "./index";

// Generated by `client_instruction_vectors` in lifi-intent-svm
// (tests/litesvm-unit/core_tests/axelar_litesvm). Requests use the reference
// builder's JSON shape; results there are unprefixed hex and decimal strings.
type Request = Record<string, any>;

function run(r: Request): unknown {
  const hex = (v: string) => `0x${v}` as const;
  const message = r.message as AxelarMessage;
  switch (r.operation) {
    case "config":
      return decodeAxelarConfig(hex(r.data));
    case "route":
      return decodeAxelarRoute(hex(r.data));
    case "routeAddress":
      return { route: axelarRouteAddress(r.name) };
    case "setChainMapping":
      return axelarSetChainMappingInstruction({
        owner: r.payer,
        name: r.name,
        chainId: BigInt(r.chainId),
        kind: r.kind,
      });
    case "initialize":
      return axelarInitializeInstruction({
        payer: r.payer,
        owner: r.owner,
        gateway: r.gateway,
        gasService: r.gasService,
        chainName: r.chainName,
      });
    case "transferOwnership":
      return axelarTransferOwnershipInstruction({
        owner: r.owner,
        newOwner: r.newOwner,
      });
    case "renounceOwnership":
      return axelarRenounceOwnershipInstruction({ owner: r.owner });
    case "fund":
      return axelarFundInstruction({
        payer: r.payer,
        gasService: r.gasService,
        messageId: message.cc_id.message_id,
        amount: BigInt(r.amount),
      });
    case "submit":
      return axelarSubmitInstruction({
        payer: r.payer,
        gateway: r.gateway,
        gasService: r.gasService,
        source: r.source,
        destinationChain: r.destinationChain,
        recipientOracle: hex(r.recipientOracle),
        payload: hex(r.payload),
        gasAmount: BigInt(r.gasAmount),
        destinationConfig: r.destinationConfig && hex(r.destinationConfig),
        deliveryMode: r.deliveryMode,
        consume: r.consume,
      });
    case "approve":
      return axelarApprovalSteps({
        payer: r.payer,
        gateway: r.gateway,
        message,
        executeData: hex(r.executeData),
      });
    case "receive":
      return axelarReceiveSteps({
        payer: r.payer,
        gateway: r.gateway,
        message,
        payload: hex(r.payload),
        sourceChainId: BigInt(r.sourceChainId),
        sourceKind: r.sourceKind as AxelarAddressKind,
      });
  }
  throw new Error(`Unknown operation ${r.operation}`);
}

const normalize = (value: unknown): unknown =>
  JSON.parse(
    JSON.stringify(value, (_, v) =>
      typeof v === "bigint"
        ? v.toString()
        : typeof v === "string" && v.startsWith("0x")
          ? v.slice(2)
          : v,
    ),
  );

// Expected failure per Rust `reject …` vector; an unmapped reject vector fails.
const REJECTIONS: Record<string, RegExp> = {
  "reject self-relay gas": /^Relayed needs positive gas; SelfRelay needs zero$/,
  "reject relayed zero gas":
    /^Relayed needs positive gas; SelfRelay needs zero$/,
  "reject oversized proof": /^Proof exceeds 320 bytes$/,
  "reject unknown payload magic":
    /^Payload is not a fill or not-filled description$/,
  "reject zero fund": /^Funding amount must be positive$/,
  "reject batched approval": /^Expected exactly one approved message$/,
  "reject substituted approval": /^Signed approval is for a different message$/,
  "reject receive payload hash": /^Payload hash mismatch$/,
  "reject receive message bounds":
    /^Axelar message field outside gateway bounds$/,
  "reject receive zero chain": /^Source chain ID must be a nonzero u128$/,
  "reject receive sender kind": /^Invalid Stellar contract address$/,
};

type Vector = {
  name: string;
  request: Request;
  result?: unknown;
  error?: true;
};

describe("Axelar builders match the Rust reference vectors", () => {
  for (const v of vectors as Vector[]) {
    it(v.name, () => {
      if (v.error) {
        const expected = REJECTIONS[v.name];
        if (!expected)
          throw new Error(`No expected error mapped for vector "${v.name}"`);
        expect(() => run(v.request)).toThrow(expected);
      } else expect(normalize(run(v.request))).toEqual(v.result);
    });
  }
});

describe("axelarReceiveSteps", () => {
  it("derives a Solana-kind sender from the base58 source address", () => {
    const r = (vectors as Vector[]).find(
      (v) => v.name === "receive from evm",
    )!.request;
    const source = base58.encode(new Uint8Array(32).fill(7));
    const message = { ...(r.message as AxelarMessage), source_address: source };
    const plan = axelarReceiveSteps({
      payer: r.payer,
      gateway: r.gateway,
      message,
      payload: `0x${r.payload}`,
      sourceChainId: 77n,
      sourceKind: "solana",
    });
    // Envelope: u8 tag, u32-LE length, OIF message = application(32) ||
    // u16-BE count || u16-BE size || proof.
    const envelope = toBytes(r.payload);
    const oif = envelope.subarray(5, 5 + (envelope[1]! | (envelope[2]! << 8)));
    const size = (oif[34]! << 8) | oif[35]!;
    const [expected] = findSolanaProgramAddress(
      [
        new TextEncoder().encode("attestation"),
        base58.decode(plan.config),
        u128Le(77n),
        decodeAxelarAddress(source, "solana"),
        oif.subarray(0, 32),
        keccak256(oif.subarray(36, 36 + size), "bytes"),
      ],
      INTENTS_PROTOCOL_PROGRAM,
    );
    expect(plan.proof).toBe(expected);
    expect(plan.steps.map((s) => s.name)).toEqual(["execute", "register"]);
    expect(() =>
      axelarReceiveSteps({
        payer: r.payer,
        gateway: r.gateway,
        message: { ...message, source_address: `${source}1` },
        payload: `0x${r.payload}`,
        sourceChainId: 77n,
        sourceKind: "solana",
      }),
    ).toThrow(/^Invalid Solana address/);
  });
});

describe("axelarSubmitInstruction payload commitment", () => {
  // Mirrors pinned `decode_fill_description`: magic + 172-byte minimum only; the
  // common payload's u16 length prefixes are not parsed on-chain.
  const r = (vectors as Vector[]).find(
    (v) => v.name === "submit self-relay solana route",
  )!.request;
  const fill = toBytes(r.payload);
  const local = (payload: Uint8Array) =>
    axelarSubmitInstruction({
      payer: r.payer,
      gateway: r.gateway,
      gasService: r.gasService,
      source: r.source,
      destinationChain: r.destinationChain,
      recipientOracle: `0x${r.recipientOracle}`,
      payload,
      gasAmount: 0n,
      destinationConfig: r.destinationConfig && `0x${r.destinationConfig}`,
      deliveryMode: "SelfRelay",
    }).keys.at(-1)!.pubkey;

  it("excludes the fill timestamp and commits to every other byte", () => {
    const base = local(fill);
    const retimed = fill.slice();
    retimed[71] = fill[71]! ^ 1;
    expect(local(retimed)).toBe(base);
    const trailing = Uint8Array.of(...fill, 0);
    const misprefixed = fill.slice();
    misprefixed[168] = 0xff;
    expect(local(trailing)).not.toBe(base);
    expect(local(misprefixed)).not.toBe(base);
  });

  it("rejects descriptions below the minimum length", () => {
    expect(() => local(fill.subarray(0, 171))).toThrow(
      /^Payload is not a fill or not-filled description$/,
    );
  });
});
